spring.application.name: atm
eureka:
  client.serviceUrl.defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true

feign:
  eureka:
    enabled: true
  MaxAutoRetries: 0 #(2)
  MaxAutoRetriesNextServer: 1 #(3)
  ReadTimeout: 1000 #(4)