spring.application.name: atm
eureka:
  client.serviceUrl.defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true

feign:
  eureka:
    enabled: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  ReadTimeout: 500
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500